title: AI Ejada Manifesto
description: Software Development Life Cycle Framework for AI-Driven Solutions
baseurl: "/AI-Ejada-Manifesto.github.io"
url: "https://m-elsherbeny.github.io"

markdown: kramdown
highlighter: rouge
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
header_pages:
  - sdlc/README.md
  - ai-principles/README.md
  - contributing.md

# SEO
author: M-Elsherbeny
twitter_username: your-twitter
github_username: M-Elsherbeny

# Build settings
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock