site_name: AI Ejada Playbook
site_url: https://m-elsherbeny.github.io/AI-Ejada-Manifesto.github.io
site_description: Software Development Life Cycle Framework for AI-Driven Solutions
site_author: M-Elsherbeny

repo_url: https://github.com/M-Elsherbeny/AI-Ejada-Manifesto.github.io
edit_uri: ""

theme:
  name: material
  font:
    text: Roboto
  palette:
    primary: black
  logo: assets/ejada_logo.png
  favicon: assets/ejada_logo.png
  features:
    - navigation.instant
    - navigation.indexes

plugins:
  - search
  - git-revision-date-localized
  - awesome-pages

markdown_extensions:
  - meta
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.pathconverter
  - pymdownx.tabbed
  - pymdownx.tasklist

nav:
  - Home: index.md
  - SDLC Framework:
    - Overview: sdlc/SDLC.md
    # - Planning: sdlc/planning.md
    # - Design: sdlc/design.md
    # - Development: sdlc/development.md
    # - Testing: sdlc/testing.md
    # - Deployment: sdlc/deployment.md
    # - Maintenance: sdlc/maintenance.md
  - Tracker:
    - AI Component Development Tracker: Tracker/AI-Component-Development-Tracker.md
    - AI Component Identification Card: Tracker/AI-Component-Identification-Card.md
    
  - R&D:
    # - Overview: R&D/index.md
    - Lifecycle Model: R&D/rd_lifecycle_model.md
    - Project Documentation Template: R&D/rd_project_documentation_template.md
    - Proposal Template: R&D/rd_proposal_template.md
  - Tools & Resources: tools.md
  - Contributing: CONTRIBUTING.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/M-Elsherbeny
  generator: false

copyright: Copyright &copy; 2025 M-Elsherbeny - AI Ejada Playbook